import subprocess
import sys
import os
import ast
import multiprocessing

# Exclude heavy libraries that PyQt/Astral might try to pull in unnecessarily
EXCLUDES = [
    "tkinter", "unittest", "pydoc", "sqlite3", "pdb",
    "matplotlib", "scipy", "PyQt5", "PySide2", "PySide6",
    "IPython", "notebook", "jupyter"
]

# Core dependencies that Nuitka's static analysis might miss
BASE_HIDDEN_IMPORTS = [
    "urllib.request",
    "urllib.error",
    "subprocess",
    "hashlib",
    "swisseph",
    "pytz",
    "timezonefinder",
    "astral",
    "geopy"
]

def get_dynamic_imports(directory="dynamic_settings_modules"):
    """Scans for 3rd-party dependencies inside the plugins."""
    found_imports = set()
    if not os.path.exists(directory):
        return []

    for filename in os.listdir(directory):
        if filename.endswith(".py") and not filename.startswith("__"):
            filepath = os.path.join(directory, filename)
            try:
                with open(filepath, "r", encoding="utf-8") as f:
                    tree = ast.parse(f.read(), filename=filepath)
                for node in ast.walk(tree):
                    if isinstance(node, ast.Import):
                        for alias in node.names:
                            found_imports.add(alias.name.split('.')[0])
                    elif isinstance(node, ast.ImportFrom):
                        if node.module:
                            found_imports.add(node.module.split('.')[0])
            except Exception as e:
                print(f"⚠️ [WARNING] Could not parse {filename} for imports: {e}")
                
    return list(found_imports)

def map_baked_plugins(directory="dynamic_settings_modules"):
    """Creates an __init__.py with __all__ so the compiled app knows what is baked inside."""
    if not os.path.exists(directory):
        return
        
    plugins = []
    for filename in os.listdir(directory):
        name, ext = os.path.splitext(filename)
        if ext == ".py" and not name.startswith("__"):
            plugins.append(name)
            
    init_path = os.path.join(directory, "__init__.py")
    with open(init_path, "w", encoding="utf-8") as f:
        f.write(f"# AUTO-GENERATED BY BUILD SCRIPT\n")
        f.write(f"__all__ = {repr(plugins)}\n")
        
    print(f"📦 Mapped {len(plugins)} plugins for baking: {plugins}")

def build_app():
    # Detect CPU cores to maximize compilation speed
    max_jobs = str(multiprocessing.cpu_count())
    
    command = [
        sys.executable, "-m", "nuitka",
        "--standalone",                        
        "--output-dir=dist",                   
        "--output-filename=AstroBasics",       
        "--windows-console-mode=disable",      
        "--windows-icon-from-ico=icon.ico",    
        
        # --- 🚀 MAXIMUM SPEED & EFFICIENCY FLAGS 🚀 ---
        f"--jobs={max_jobs}",                  # Use all CPU cores for compiling
        "--lto=yes",                           # Link-Time Optimization: Faster app, smaller EXE
        "--assume-yes-for-downloads",          # Auto-download 'ccache' to make caching work perfectly
        
        "--enable-plugin=pyqt6",               
        "--enable-plugin=anti-bloat",          
        
        # --- PHYSICAL DATA INCLUSIONS ---
        f"--include-data-files={os.path.abspath('icon.ico')}=icon.ico",
        f"--include-data-dir={os.path.abspath('ephe')}=ephe",
        
        # --- MODULE INCLUSIONS ---
        "--include-package=dynamic_settings_modules",
        
        # --- CRITICAL PACKAGE DATA ---
        "--include-package-data=timezonefinder",
        "--include-package-data=pytz",
        "--include-package-data=tzdata",
        "--include-package-data=astral"
    ]
    
    dynamic_imports = get_dynamic_imports()
    all_hidden_imports = set(BASE_HIDDEN_IMPORTS + dynamic_imports)

    print("\n--- Discovered Dependencies ---")
    for hi in all_hidden_imports:
        if hi not in EXCLUDES:
            print(f" -> Injecting: {hi}")
            command.append(f"--include-module={hi}")

    print("\n--- Excluding Bloatware ---")
    for exc in EXCLUDES:
        command.append(f"--nofollow-import-to={exc}")

    command.append("main.py")

    print(f"\n🚀 Running Nuitka build across {max_jobs} CPU threads...")
    print("⚡ Link-Time Optimization (LTO) and C-Cache enabled.")
    map_baked_plugins()
    
    try:
        subprocess.run(command, check=True)
        print("\n✅ Build complete! Check the 'dist/AstroBasics.dist' folder.")
    except subprocess.CalledProcessError as e:
        print(f"\n❌ Build failed with error code: {e.returncode}")

if __name__ == "__main__":
    build_app()